projects:
  crudAppSyncApi:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: eu-west-2
        apiId: c2zdhezrnfh55dyaepvcpppofi
        maxDepth: 2
extensions:
  amplify:
    version: 3
