"AWSTemplateFormatVersion" : "2010-09-09"

# VPC 
# IGW
# Route Tables
# Subnets
# Subnet A
# Subnet B
# Subnet C

# VPC
Resources:
  VPC:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpc.html
    Type: AWS::EC2::VPC
    Properties:
      # CidrBlock: !Ref VpcCidrBlock
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      # Tags:
        # - Key: Name
        #   Value: !Sub "${AWS::StackName}VPC"

